services:
  postgres:
    image: docker.io/library/postgres:17-alpine
    container_name: postgres
    networks:
      - nextcloud-network
    environment:
      POSTGRES_DB: ${NEXTCLOUD_DB_NAME}
      POSTGRES_USER: ${NEXTCLOUD_DB_USER}
      POSTGRES_PASSWORD: ${NEXTCLOUD_DB_PASSWORD}
    volumes:
      - nextcloud-postgres-data:/var/lib/postgresql/data:Z
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${NEXTCLOUD_DB_USER}", "-d", "${NEXTCLOUD_DB_NAME}"]

  redis:
    image: docker.io/library/redis:8.4-alpine
    container_name: redis
    networks:
      - nextcloud-network
    volumes:
      - nextcloud-redis-data:/data:Z
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  nextcloud:
    image: docker.io/library/nextcloud:production-fpm-alpine
    container_name: nextcloud
    networks:
      - nextcloud-network
      - mail
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${NEXTCLOUD_DB_NAME}
      POSTGRES_USER: ${NEXTCLOUD_DB_USER}
      POSTGRES_PASSWORD: ${NEXTCLOUD_DB_PASSWORD}
      REDIS_HOST: redis
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: "${NEXTCLOUD_HOSTNAME}"
      TRUSTED_PROXIES: "*"
      OVERWRITEHOST: ${NEXTCLOUD_HOSTNAME}
      OVERWRITEPROTOCOL: https
    volumes:
      - nextcloud-data:/var/www/html:Z
      - nextcloud-config-data:/var/www/html/config:Z
    restart: always
    depends_on:
      - postgres
      - redis

  nginx:
    image: docker.io/library/nginx:alpine
    container_name: nginx
    networks:
      - nextcloud-network
      - waf
    volumes:
      - nextcloud-data:/var/www/html:Z
      - ./nginx.conf:/etc/nginx/nginx.conf:ro,Z
    restart: always
    depends_on:
      - nextcloud

networks:
  nextcloud-network:
    name: nextcloud-network
    driver: bridge
  waf:
    external: true
  mail:
    external: true

volumes:
  nextcloud-postgres-data:
    name: nextcloud-postgres-data
  nextcloud-redis-data:
    name: nextcloud-redis-data
  nextcloud-data:
    name: nextcloud-data
  nextcloud-config-data:
    name: nextcloud-config-data