services:

  redis-cache:
    container_name: frappe-redis-cache
    image: docker.io/library/redis:6.2-alpine
    restart: unless-stopped
    volumes:
      - type: tmpfs
        target: /data
        tmpfs:
          mode: 1777
    networks:
      - frappe-network

  redis-queue:
    container_name: frappe-redis-queue
    image: docker.io/library/redis:6.2-alpine
    restart: unless-stopped
    volumes:
      - redis-queue-data:/data
    networks:
      - frappe-network

volumes:
  redis-queue-data:
