services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:15.1.0
    hostname: ${MAILSERVER_HOSTNAME}
    container_name: mailserver
    restart: always
    cap_add:
      - NET_ADMIN
    networks:
      - mail
      - keycloak
      - ipa
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
      - "143:143"
    environment:
      - ACCOUNT_PROVISIONER=LDAP
      - LDAP_SERVER_HOST=ldap://freeipa
      - LDAP_SEARCH_BASE=cn=accounts,${FREEIPA_BASE_DN}
      - LDAP_BIND_DN=${MAILSERVER_LDAP_BIND_DN}
      - LDAP_BIND_PW=${MAILSERVER_LDAP_BIND_PASSWORD}
      - LDAP_QUERY_FILTER_USER=(&(objectClass=inetOrgPerson)(mail=%s)(!(|(uid=admin)(memberOf=cn=system-accounts,${FREEIPA_GROUP_DN}))))
      - LDAP_QUERY_FILTER_GROUP=(&(objectClass=groupOfNames)(mail=%s))
      - LDAP_QUERY_FILTER_ALIAS=(&(objectClass=inetOrgPerson)(mail=%s)(!(|(uid=admin)(memberOf=cn=system-accounts,${FREEIPA_GROUP_DN}))))
      - LDAP_QUERY_FILTER_DOMAIN=(|(&(mail=*@%s)(objectClass=inetOrgPerson))(&(mailGroupMember=*@%s)(objectClass=groupOfNames)))
      - DOVECOT_PASS_FILTER=(&(objectClass=inetOrgPerson)(uid=%n)(!(|(uid=admin)(memberOf=cn=system-accounts,${FREEIPA_GROUP_DN}))))
      - DOVECOT_USER_FILTER=(&(objectClass=inetOrgPerson)(uid=%n)(!(|(uid=admin)(memberOf=cn=system-accounts,${FREEIPA_GROUP_DN}))))
      - DOVECOT_AUTH_BIND=yes
      - ENABLE_OAUTH2=1
      - OAUTH2_INTROSPECTION_URL=http://${KEYCLOAK_HOSTNAME}/realms/netzor/protocol/openid-connect/token/introspect
      - OAUTH2_USERNAME_ATTRIBUTE=email
      - POSTMASTER_ADDRESS=postmaster@${DOMAIN}
      - ENABLE_RSPAMD=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - DOVECOT_USER_ATTRS==uid=5000,=gid=5000,=home=/var/mail/%d/%n,=mail=maildir:/var/mail/%d/%n
    volumes:
      - mailserver-data:/var/mail:Z
      - mailserver-state:/var/mail-state/:Z
      - mailserver-logs:/var/log/mail/:Z
      - mailserver-config:/tmp/docker-mailserver:Z
      - ${PWD}/mail/dovecot-oauth2.conf.ext:/etc/dovecot/dovecot-oauth2.conf.ext:Z
    extra_hosts:
      - "${KEYCLOAK_HOSTNAME}:host-gateway"

  roundcube:
    image: docker.io/roundcube/roundcubemail:1.6.12-apache
    container_name: roundcube
    hostname: ${ROUNDCUBE_HOSTNAME}
    restart: always
    networks:
      - mail
      - keycloak
      - waf
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=${MAILSERVER_HOSTNAME}
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      - ROUNDCUBEMAIL_SMTP_SERVER=${MAILSERVER_HOSTNAME}
      - ROUNDCUBEMAIL_SMTP_PORT=587
    volumes:
      - roundcube-config:/var/www/html/config:Z
      - roundcube-db:/var/roundcube/db:Z
    extra_hosts:
      - "${KEYCLOAK_HOSTNAME}:host-gateway"

networks:
  mail:
    driver: bridge
    name: mail
  keycloak:
    external: true
  ipa:
    external: true
  waf:
    external: true

volumes:
  mailserver-data:
    name: mailserver-data
  mailserver-state:
    name: mailserver-state
  mailserver-logs:
    name: mailserver-logs
  mailserver-config:
    name: mailserver-config
  roundcube-config:
    name: roundcube-config
  roundcube-db:
    name: roundcube-db
