services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:15.1.0
    hostname: ${MAILSERVER_HOSTNAME}
    container_name: mailserver
    restart: always
    cap_add:
      - NET_ADMIN
    networks:
      mail:
        aliases:
          - ${MAILSERVER_HOSTNAME}
      keycloak: {}
      ipa: {}
      waf: {}
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
      - "143:143"
    environment:
      - ACCOUNT_PROVISIONER=LDAP
      - LDAP_SERVER_HOST=ldap://freeipa
      - LDAP_SEARCH_BASE=cn=accounts,${FREEIPA_BASE_DN}
      - LDAP_BIND_DN=${MAILSERVER_LDAP_BIND_DN}
      - LDAP_BIND_PW=${MAILSERVER_LDAP_BIND_PASSWORD}
      - LDAP_QUERY_FILTER_USER=(&(objectClass=inetOrgPerson)(mail=%s)(!(|(uid=admin)(memberOf=cn=system-accounts,${FREEIPA_GROUP_DN}))))
      - LDAP_QUERY_FILTER_GROUP=(&(objectClass=groupOfNames)(mail=%s))
      - LDAP_QUERY_FILTER_ALIAS=(&(objectClass=inetOrgPerson)(mail=%s)(!(|(uid=admin)(memberOf=cn=system-accounts,${FREEIPA_GROUP_DN}))))
      - LDAP_QUERY_FILTER_DOMAIN=(|(&(mail=*@%s)(objectClass=inetOrgPerson))(&(mailGroupMember=*@%s)(objectClass=groupOfNames)))
      - DOVECOT_PASS_FILTER=(&(objectClass=inetOrgPerson)(uid=%n)(!(|(uid=admin)(memberOf=cn=system-accounts,${FREEIPA_GROUP_DN}))))
      - DOVECOT_USER_FILTER=(&(objectClass=inetOrgPerson)(uid=%n)(!(|(uid=admin)(memberOf=cn=system-accounts,${FREEIPA_GROUP_DN}))))
      - DOVECOT_AUTH_BIND=yes
      - ENABLE_OAUTH2=1
      - OAUTH2_INTROSPECTION_URL=http://${KEYCLOAK_HOSTNAME}/realms/netzor/protocol/openid-connect/token/introspect
      - OAUTH2_USERNAME_ATTRIBUTE=email
      - ENABLE_SASLAUTHD=1
      - SASLAUTHD_MECHANISMS=ldap
      - SASLAUTHD_LDAP_SERVER=ldap://freeipa
      - SASLAUTHD_LDAP_BIND_DN=${MAILSERVER_LDAP_BIND_DN}
      - SASLAUTHD_LDAP_PASSWORD=${MAILSERVER_LDAP_BIND_PASSWORD}
      - SASLAUTHD_LDAP_SEARCH_BASE=cn=accounts,${FREEIPA_BASE_DN}
      - SASLAUTHD_LDAP_FILTER=(&(objectClass=inetOrgPerson)(uid=%U)(!(|(uid=admin)(memberOf=cn=system-accounts,${FREEIPA_GROUP_DN}))))
      - POSTMASTER_ADDRESS=postmaster@${DOMAIN}
      - ENABLE_RSPAMD=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
    volumes:
      - mailserver-data:/var/mail:Z
      - mailserver-state:/var/mail-state/:Z
      - mailserver-logs:/var/log/mail/:Z
      - mailserver-config:/tmp/docker-mailserver:Z
      - ./dovecot-oauth2.conf.ext:/etc/dovecot/dovecot-oauth2.conf.ext:Z
    extra_hosts:
      - "${KEYCLOAK_HOSTNAME}:host-gateway"

  roundcube:
    image: docker.io/roundcube/roundcubemail:latest
    container_name: roundcube
    restart: always
    networks:
      - mail
      - keycloak
      - waf
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_DEFAULT_HOST=${MAILSERVER_HOSTNAME}
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      - ROUNDCUBEMAIL_SMTP_SERVER=${MAILSERVER_HOSTNAME}
      - ROUNDCUBEMAIL_SMTP_PORT=587
      - ROUNDCUBEMAIL_PLUGINS=archive,zipdownload
      - ROUNDCUBEMAIL_OAUTH_PROVIDER=generic
      - ROUNDCUBEMAIL_OAUTH_PROVIDER_NAME=Keycloak
      - ROUNDCUBEMAIL_OAUTH_CLIENT_ID=${ROUNDCUBE_OIDC_CLIENT_ID}
      - ROUNDCUBEMAIL_OAUTH_CLIENT_SECRET=${ROUNDCUBE_OIDC_CLIENT_SECRET}
      - ROUNDCUBEMAIL_OAUTH_AUTH_URI=http://${KEYCLOAK_HOSTNAME}/realms/netzor/protocol/openid-connect/auth
      - ROUNDCUBEMAIL_OAUTH_TOKEN_URI=http://${KEYCLOAK_HOSTNAME}/realms/netzor/protocol/openid-connect/token
      - ROUNDCUBEMAIL_OAUTH_IDENTITY_URI=http://${KEYCLOAK_HOSTNAME}/realms/netzor/protocol/openid-connect/userinfo
      - ROUNDCUBEMAIL_OAUTH_VERIFY_PEER=false
      - ROUNDCUBEMAIL_OAUTH_SCOPE=email openid profile
      - ROUNDCUBEMAIL_OAUTH_IDENTITY_FIELDS=email
      - ROUNDCUBEMAIL_OAUTH_LOGIN_REDIRECT=true
    volumes:
      - roundcube-config:/var/www/html/config:Z
    extra_hosts:
      - "${KEYCLOAK_HOSTNAME}:host-gateway"

networks:
  mail:
    driver: bridge
    name: mail
  keycloak:
    external: true
  ipa:
    external: true
  waf:
    external: true

volumes:
  mailserver-data:
  mailserver-state:
  mailserver-logs:
  mailserver-config:
    external: true
  roundcube-config:
    external: true
