HOST=$N8N_HOSTNAME
SERVER_NAMES+=("$HOST")

BUNKER_ENV+=(
    -e "${HOST}_USE_REVERSE_PROXY=yes"
    -e "${HOST}_REVERSE_PROXY_HOST=http://n8n_app:5678"
    -e "${HOST}_SECURITY_MODE=detect"
    -e "${HOST}_USE_LETS_ENCRYPT=yes"
)
